version: "3.8"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.5
    container_name: murmur-kafka-broker
    ports:
      - "9092:9092"
    environment:
      # Run Kafka in KRaft mode (No Zookeeper required)
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Automatically create our required topics on startup
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      # REQUIRED: Bitnami will crash without this when using PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - murmur_kafka_data:/bitnami/kafka

volumes:
  murmur_kafka_data:
    driver: local