apiVersion: v1
kind: Service
metadata:
  name: murmur-kafka-broker
  namespace: default
  labels:
    app: murmur-kafka
spec:
  ports:
  - name: tcp-kafka
    port: 9092
    targetPort: 9092
  - name: tcp-controller
    port: 9093
    targetPort: 9093
  selector:
    app: murmur-kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: murmur-kafka
  namespace: default
spec:
  selector:
    matchLabels:
      app: murmur-kafka
  serviceName: "murmur-kafka-broker"
  replicas: 1
  template:
    metadata:
      labels:
        app: murmur-kafka
    spec:
      containers:
      - name: kafka
        image: docker.io/bitnami/kafka:3.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        # Run Kafka in KRaft mode (No Zookeeper)
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "1@murmur-kafka-0.murmur-kafka-broker.default.svc.cluster.local:9093"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"